# Generated by Django 4.2.28 on 2026-02-26 10:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cart_app', '0003_order_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='payment_method',
            field=models.CharField(choices=[('online', 'Online (Razorpay)'), ('cod', 'Cash on Delivery')], default='online', max_length=10),
        ),
        migrations.AlterField(
            model_name='order',
            name='status',
            field=models.CharField(choices=[('created', 'Created'), ('paid', 'Paid'), ('failed', 'Failed'), ('placed', 'Placed (COD)'), ('cancelled', 'Cancelled'), ('delivered', 'Delivered')], default='created', max_length=20),
        ),
    ]
