# Generated by Django 4.2.28 on 2026-02-26 10:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cart_app', '0004_order_payment_method_alter_order_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='is_paid',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='order',
            name='status',
            field=models.CharField(choices=[('placed', 'Placed'), ('packed', 'Packed'), ('shipped', 'Shipped'), ('delivered', 'Delivered'), ('cancelled', 'Cancelled'), ('payment_pending', 'Payment Pending'), ('payment_failed', 'Payment Failed'), ('created', 'Created (Old)'), ('paid', 'Paid (Old)'), ('failed', 'Failed (Old)')], default='placed', max_length=30),
        ),
    ]
