# Generated by ChatGPT on 2026-02-26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('moc_app', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='sizes',
            field=models.CharField(blank=True, help_text='Comma-separated sizes e.g. S,M,L,XL', max_length=120),
        ),
        migrations.AddField(
            model_name='product',
            name='colors',
            field=models.CharField(blank=True, help_text='Comma-separated colors e.g. Black,Blue,Red', max_length=120),
        ),
        migrations.AddField(
            model_name='product',
            name='brand',
            field=models.CharField(blank=True, max_length=120),
        ),
        migrations.AddField(
            model_name='product',
            name='material',
            field=models.CharField(blank=True, max_length=120),
        ),
    ]
